### ISSUE TITLE
Error in nova 4 when attaching links that have image.

### ISSUE THREAD

**Issue by tractorcow** [advoor/nova-editor-js#100]
When attaching a link and viewing it I receive this error.

```
Something went wrong: Found extra param `imageUrl`
```

This seems to be a regression in https://github.com/advoor/nova-editor-js/pull/70 where the structure of the link json was changed, but the config validation was not updated to match, nor was the `link.blade.php` renderer.

```blade
<div class="editor-js-block">
    <div class="editor-js-link">
        <a href="{{ $link }}" class="editor-js-link-content">
            @if (!empty($meta['image']['url']))
                <div class="editor-js-link-image" style="background-image: url('{{ $meta['image']['url'] }}');"></div>
            @endif

            <h4>{{ $meta['title'] }}</h4>
            <p>
                {{ $meta['description'] }}
            </p>
            <p>
                <small>{{ $link }}</small>
            </p>
        </a>
    </div>
</div>

```

**Comment by roelofr** [comment]
I don't have access to a Nova 4 installation (my license has expired).

I'll try to get this situation to arise on Nova 3, but that's all I can do.

**Comment by tractorcow** [comment]
The bug seems to be only in the nova 4 version of this code, so you won't be able to reproduce it on the newest nova-3 compatible version, I'm afraid.

**Comment by roelofr** [comment]
This has been repaired in v3.3.0
