### ISSUE TITLE
Resize uploaded images

### ISSUE THREAD

**Issue by lorado** [advoor/nova-editor-js#12]
Hi, as I already mentioned - great work, thanks for the library!

I thought about possible improvements. Would it be possible to add support for [spatie medialibrary](https://github.com/spatie/laravel-medialibrary)? Resize/Multiple sizes of images would become so easy.

Alternatively some resize params would be nice, like in [advanced image field](https://github.com/ctessier/nova-advanced-image-field)

What do yo think?

**Comment by advoor** [comment]
@lorado I do like the idea, but not sure how the integration would work, specially with it having it's own migration and configuration options. 

For image manipulation looks like the media library uses [spatie/image](https://github.com/spatie/image) , so I could integrate that quite easily, giving the ability to define different sizes?

**Comment by lorado** [comment]
I didn't dig there deep, but it seems, that probably usage of spatie/image would be enough.

> For image manipulation looks like the media library uses spatie/image , so I could integrate that quite easily, giving the ability to define different sizes?

Yeah, go for it =)

**Comment by advoor** [comment]
Hey @lorado, @mpanius finally got some time to work on this! 

https://github.com/advoor/nova-editor-js/pull/15 - I'll do a release this weekend after I've tested this a bit more, but it would be good to get some initial feedback. Not tested with the S3 driver, but I think it should work just fine.

**Comment by lorado** [comment]
Oh oh! That is awesome. I am currently developing one project, where I use your lib. Unfortunately for you I can test local uploads only. I don't use S3...
When I get time this weekend, I will also test a little bit your branch ;)

**Comment by advoor** [comment]
Tested a bit more and it looked good enough for a release :) Let me know if you have any issues!

**Comment by lorado** [comment]
Just a quick respond: This feature works well for me! Thank you very much!

**Comment by mira-thakkar** [comment]
@lorado hey have you used s3 driver with this package & media library?

**Comment by lorado** [comment]
@mira-thakkar hi, I was using local storage driver. Never tried s3, so can't help you there, sorry
