### ISSUE TITLE
Store uploaded image to medialibrary

### ISSUE THREAD

**Issue by mpanius** [advoor/nova-editor-js#13]
As far as i have seen, you are now using Spatie/Image for optimizing uploaded images. 
Maybe better way will be using full Spatie/laravel-medialibrary (https://github.com/spatie/laravel-medialibrary), which also stores image information associated to object (thus making easier managing it later)?

**Comment by advoor** [comment]
I guess it would make sense to implement the media library at some point, so better off doing it now. I'll have a play around to see what would be the best way to get this integrated.

**Comment by lorado** [comment]
Oh well, it is kinda related to #12 

If you integrate medialibrary, you could solve these two tickets

**Comment by advoor** [comment]
Will still look into integrating media library at some point; just not had the spare time recently :( Hopefully the recent release should take care of any immediate requirements

**Comment by chrispage1** [comment]
Hey, nice plugin! Was this particular issue ever resolved?

**Comment by roelofr** [comment]
Closing this as there's no capacity to incorporate this.
