### ISSUE TITLE
Nullable columns issue

### ISSUE THREAD

**Issue by lorado** [advoor/nova-editor-js#14]
When I make a nullable column, and don't change any content in NovaEditorJs field, it sends `null` to the backend, what is the behaviour I expect.

The problem is, when `generateHtmlOutput()` is used, it returns following error: "Something went wrong: JSON is empty". And it is pretty weird, when I don't enter any content, but on entity preview I such an error. It just feels broken.

So my suggestions are:

- Either change `generateHtmlOutput()` method, and simply return empty string, if given value is `null`
- OR change Fiel behaviour, so that already on initialisation value gets evaluated and generated as JSON. Output JSON will simply contain empty blocks array, something like this: `{"time":1558480815671,"blocks":[],"version":"2.12.4"}`

What do you think?

**Comment by advoor** [comment]
Hmm, I think it makes sense to just output an empty string if the value is null. Ill get this with the next release :)

**Comment by advoor** [comment]
Will now return an empty string instead of the error in version 0.6 :)
