### ISSUE TITLE
Conflict with Nova shortcuts

### ISSUE THREAD

**Issue by MarceauKa** [advoor/nova-editor-js#18]
Nova : 2.0.6+

When I type **?** or **/** in the editor, the Nova global search is focused.

**Comment by MarceauKa** [comment]
https://github.com/laravel/nova-issues/issues/1733

**Comment by Jaspur** [comment]
@advoor 👍

**Comment by advoor** [comment]
@MarceauKa @Jaspur Thanks for this guys! Published the fix in the new release
