### ISSUE TITLE
Remove image when delete block

### ISSUE THREAD

**Issue by Krato** [advoor/nova-editor-js#3]
Hello, first, thank you for this amazing tool.

Image upload is working fine, but will be great to remove the image if a Image block is deleted. 

A way to customize the storage disk will be useful also.

Thanks!

**Comment by advoor** [comment]
Thanks @Krato !

I do like the idea, however it doesn't looks like the Editor JS API can help with this as it currently stands. Raised an issue hoping they can build a configurable endpoint - i rather this be in the core then me hacking on some listeners.

I've deployed a new version which gives you the ability to specify the path and disk - please let me know if you come across any issues with this.

**Comment by lorado** [comment]
Hi @advoor,

I just thought about possible implementations... How about this idea:
Before updated content is stored in DB, determine, if there are some image blocks in old version of content, that do not exist in the new version. Then parse file path from url (and all thumbnails) and remove these files.

It feels like a hack, but it should work

**Comment by rik43** [comment]
+1 @lorado 
without nova, i used this code:

```
    private function deleteNotUsedImages($newBlocks, $oldBlocks)
    {
        $images = [];

        // previous images list
        foreach ($oldBlocks as $block) {
            if ($block['type'] === 'image') {
                $url = $block['data']['file']['url'];
                $images[$url] = 1;
            }
        }
        // exlude existed in new version
        foreach ($newBlocks as $block) {
            if ($block['type'] === 'image') {
                $url = $block['data']['file']['url'];
                unset($images[$url]);
            }
        }
        // drop files
        foreach ($images as $image => $temp) {
            $file = public_path($image);
            if (is_file($file)) unlink($file);
        }
    }
```

**Comment by advoor** [comment]
This is my next focus when I get some time (Y)
