### ISSUE TITLE
SyntaxError: Unexpected token < in JSON at position 0

### ISSUE THREAD

**Issue by JonathanPort** [advoor/nova-editor-js#34]
Hi, I receive the below error when using this on a resource. I've added:

```php
protected $casts = [
    'content' => 'json'
];
```

to my model. But I still get this error. My database column type for 'content' is TEXT and not JSON as the server doesn't support JSON but that shouldn't make a difference as I'm using the casts property. 

Any ideas?

The top level frontend message on the resource is:

`Something went wrong: Wrong JSON format: Syntax error`

----------------------------------------

SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at p.setInitialValue (nova-editor-js:1)
    at p.mounted (nova-editor-js:1)
    at Pt (vendor.js?id=abad729d86d183328118:1)
    at en (vendor.js?id=abad729d86d183328118:1)
    at Object.insert (vendor.js?id=abad729d86d183328118:1)
    at y (vendor.js?id=abad729d86d183328118:1)
    at p.__patch__ (vendor.js?id=abad729d86d183328118:1)
    at p.t._update (vendor.js?id=abad729d86d183328118:1)
    at p.ln.before (vendor.js?id=abad729d86d183328118:1)

**Comment by JonathanPort** [comment]
Ahhhh never mind! My mistake. In my model I was editing the property output using the getter method:

```php
/**
     * Get content attribute, applying any logic needed
     * for parsing the output.
     */
    public function getContentAttribute($content)
    {
        return NovaEditorJs::generateHtmlOutput(json_decode($content));
    }
```

This of course was being used by Nova also..

**Comment by JonathanPort** [comment]
I do actually get the same issue if I add a code block but only if the code block is the only content in the editor. Not a massive issue now I know but thought I'd reopen so you're aware, maybe something to investigate.

**Comment by techouse** [comment]
This is an issue of the Editor.js itself probably since it will fail like this if the content is invalid.

**Comment by advoor** [comment]
> I do actually get the same issue if I add a code block but only if the code block is the only content in the editor. Not a massive issue now I know but thought I'd reopen so you're aware, maybe something to investigate.

Hmm thats strange. Just played around with this a bit, and attempted to have just the code block but could not replicate it with the latest release. Unsure if it was an issue thats now fixed? If you do upgrade do let me know if you get the same errors.

**Comment by advoor** [comment]
Closing for now.
