### ISSUE TITLE
Make it translatable ?

### ISSUE THREAD

**Issue by salierg** [advoor/nova-editor-js#44]
Is this package works with Spatie Translatable ?

I was able to use it but as we store the json into another json, it's seem not to display the content on the nova index or show page. I can make some content and edit it but this is what I get when I try to see it in nova:

"Something went wrong: Field `blocks` is missing"

Any solution or fix ? Thx

**Comment by advoor** [comment]
I've not personally tried Spatie translatable with this, but looking briefly at the docs, it would conflict as it stores the data in a JSON format. 

I guess depending on how the data is stored, using a config flag, we might be able to build in support. Something to look into when time allows

**Comment by roelofr** [comment]
Closing this as there's no capacity to incorporate this (given the 2 years of silence), and it significantly increases the plugin's complexity.
