### ISSUE TITLE
Use EditorJS (NOT NOVA)

### ISSUE THREAD

**Issue by amiller911** [advoor/nova-editor-js#5]
Hello.

I dont have Laravel Nova. How i can use EditorJS in Laravel 5.7?

Thank you.

**Comment by alloyking** [comment]
Hey @amiller911,  

I think the best place to start for that question is to check out the docs here:
https://editorjs.io/getting-started

You can implement this in Laravel the same way one might just place it on a framework-less static website.

Good luck!

**Comment by advoor** [comment]
@amiller911 might also be worth looking at https://github.com/advoor/nova-editor-js/blob/master/src/NovaEditorJs.php and how the generate HTML function works.

I might extract this into a separate package at some point but for now, you can use this code as a base for your non-nova project.
