### ISSUE TITLE
Wrong AllowedTags in Paragraph with Nova 4

### ISSUE THREAD

**Issue by massimodellarovere** [advoor/nova-editor-js#62]
![image](https://user-images.githubusercontent.com/5731295/176520607-ac8a76de-107b-4668-bf4c-bd4a0d73a603.png)
CHANGE TEMPLATE 
![image](https://user-images.githubusercontent.com/5731295/176520777-ce976d6e-7f5f-4f56-93b9-e49d7a737b0e.png)

IS OK

![image](https://user-images.githubusercontent.com/5731295/176520895-6f25430f-0cb5-4b7e-b6f6-5de4e7929da8.png)

**Comment by roelofr** [comment]
Fixed in [v3.0.5](https://github.com/advoor/nova-editor-js/releases/tag/v3.0.5)
