### ISSUE TITLE
Update spatie/image

### ISSUE THREAD

**Issue by d3v4nt** [advoor/nova-editor-js#63]
Hey, thanks for updating the package to support nova 4 👏

Sadly I still can't use it in one of my projects, as it uses the newest `spatie/image` version..

<img width="1293" alt="Screenshot 2022-07-03 at 09 52 00" src="https://user-images.githubusercontent.com/33395021/177030524-3ea7c448-9a3f-4041-ae66-9cbf7cb23719.png">

It would've been really nice if you could update the composer.json in order to fix that

**Comment by advoor** [comment]
That has been merged and a release issued :)

**Comment by d3v4nt** [comment]
Oh thank you very much!
