### ISSUE TITLE
Embed block doesn't show

### ISSUE THREAD

**Issue by joostvanhoof** [advoor/nova-editor-js#67]
In a vanilla installation the embed block does not show up in the drop down list, even though it's enabled in the config file.

**Comment by Woeler** [comment]
Same issue here, it is enabled in the config, but doesnt show up in the editor.

**Comment by Woeler** [comment]
Ok, thanks for the info. That is confusing indeed. Good to know!

**Comment by roelofr** [comment]
The embed block is bound to paste events, as described in [it's readme](https://github.com/editor-js/embed).
