### ISSUE TITLE
Forked

### ISSUE THREAD

**Issue by alloyking** [advoor/nova-editor-js#7]
@advoor I forked you here: 
https://github.com/alloyking/nova-editor-js.

I don't actually know how pull requests work, nor if you even want changes I make.
But if you do I'm happy to help in anyway.  My goal isn't to take over what you have here which I think is useful. 

I made two hurried changes:
1. Modified the css to make the editor field look more like the existing fields
2. Handled the JSON parse error that shows in the console.

Thanks,
Alloyking

**Comment by advoor** [comment]
@alloyking Awesome work! Been a busy few days so sorry for the late reply, but I appreciate the contributions!

I've been working on some major changes, but ill port your fixes across for the next release!

**Comment by alloyking** [comment]
@advoor, 

Fantastic.  Let me know if you would rather have to me do a pull request.

Thanks,
Alloyking

**Comment by advoor** [comment]
Released a new version which includes the fixes. Thanks again!
