### ISSUE TITLE
Something went wrong: Field `blocks` is missing

### ISSUE THREAD

**Issue by joostvanhoof** [advoor/nova-editor-js#72]
@roelofr thanks for the previous fixes with the attribute casting. After the upgrade however (I'm using the casting now), this is what's happening:

- If I save in Nova, the editor in Nova stays blank as in it doesn't show the just saved content in the editor
- The data is correctly saved however, because I can see it in the database
- If I try to display the data in a view using `{{ $post->body }}` I get `Something went wrong: Field `blocks` is missing` while the database data I can clearly see the `blocks` in the stored data.

**Comment by joostvanhoof** [comment]
Actually, if I save an empty EditorJs field the data that's stored in the database is `"[object Object]"` so it looks like there is still something wrong with attribute casting and encoding/decoding from array to JSON?

**Comment by roelofr** [comment]
I've seen this on my site too.

It looks like it's double-encoding the JSON for some reason. Might be the cast encoding something that Nova has already encoded.

Does your data look something like this:

```
"{\"time\": 228372095, …}"
```

**Comment by joostvanhoof** [comment]
Yes:

```
"{\"time\":1658065712458,\"blocks\":[{\"id\":\"lI-Qi6ysGA\",\"type\":\"paragraph\",\"data\":{\"text\":\"fff\"}}],\"version\":\"2.25.0\"}"
```

And when saving an empty field:

```
[object Object]
```

**Comment by roelofr** [comment]
I can't seem to replicate the `[object Object]` error, my empty fields just remain empty, but I've fixed the other issue.
