### ISSUE TITLE
Error when saving the same content

### ISSUE THREAD

**Issue by joostvanhoof** [advoor/nova-editor-js#74]
@roelofr this might be related to [this issue](https://github.com/advoor/nova-editor-js/issues/72) because it's trying to save [object Object] again.

What's happening is that when I have an empty EditorJS field in Nova and type some content and save it, everything works fine.

If I then edit the resource and hit save but don't edit the content, I get:

```
3140 Invalid JSON text: "Invalid value." at position 1 in value for column 'post.body'. (SQL: update `posts` set `body` = [object Object], ...)
```

If I change the EditorJS content and save it (even if it's just adding a dot), then it does actually works.

**Comment by roelofr** [comment]
I still can't replicate this issue. Are you using the editor in a conditional field or something?

**Comment by johnpuddephatt** [comment]
I am also getting [Object object] saved in my database with 3.0.4 when updating an entry without changing the editorJs field's content.

This only happens when casting the attribute. I have the following in my model:

````
protected $casts = [
    "description" => NovaEditorJsCast::class,
];
````

If I remove this the problem goes away.

**Comment by joostvanhoof** [comment]
@roelofr this bug is still there for me, for you as well @johnpuddephatt? There is [this commit](https://github.com/waelelsawy/nova-editor-js/commit/cbf00ffcb5b82bc9f34776ceea4692200d9792b3) suggested which I think should fix it?

**Comment by roelofr** [comment]
Fixed in [v3.0.5](https://github.com/advoor/nova-editor-js/releases/tag/v3.0.5)

**Comment by johnpuddephatt** [comment]
> @roelofr this bug is still there for me, for you as well @johnpuddephatt? 

Yes it's still there in 3.0.5 when I cast the field content with Advoor\NovaEditorJs\NovaEditorJsCast. Without the casting it does not occur.

**Comment by roelofr** [comment]
But can you easily cast the stored data to HTML without the cast, the mixture of HTML and JSON is supposed to be solved by the cast.

**Comment by johnpuddephatt** [comment]
Sorry I can now confirm this problem is *not* occuring for me any longer.

With 3.0.5 I can use NovaEditorJsCast without issue.
